name: Workflow - On All Branches

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  lint:
    runs-on: ubuntu-22.04
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - uses: .github/actions/setup-hadolint
      - run: |
          source .envrc
          make lint

  test:
    runs-on: ubuntu-22.04
    name: Test
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - run: |
          source .envrc
          make test
