name: Workflow - On All Branches

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  lint:
    runs-on: ubuntu-22.04
    name: Lint
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Setup Hadolint
        uses: ./.github/actions/setup-hadolint
      - name: Run Lint
        run: |
          source .envrc
          make lint

  test:
    runs-on: ubuntu-22.04
    name: Test
    needs: lint
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Run Test
        run: |
          source .envrc
          make test
