name: Workflow - On All Branches

on:
  push:
    branches:
      - '**'
      - '!main'

env:
  DOCKER_BUILDKIT: 1
  PROJECT_DOCKER_PLATFORMS: "linux/arm64,linux/amd64"
  PROJECT_DOCKER_USER: "mundoalemio"
  PROJECT_DOCKER_REPOSITORY: "dev-base"
  PROJECT_NAME: "container-dev-base"

jobs:
  lint:
    runs-on: ubuntu-22.04
    name: Lint
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Set up hadolint
        uses: ./.github/actions/setup-hadolint
      - name: Run lint
        run: |
          make lint

  test:
    runs-on: ubuntu-22.04
    name: Test
    needs: lint
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up container-structure-test
        uses: ./.github/actions/setup-container-structure-test
      - name: Run test
        env:
          PROJECT_DOCKER_PLATFORMS: linux/amd64
        run: |
          make test
